services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONT_PORT}:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BFF_URL=${REACT_APP_BFF_URL}
  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - "${BFF_PORT}:3000"
    environment:
      - FRONT_BASE_URL=${FRONT_BASE_URL}
      - FRONT_PORT=${FRONT_PORT}
    volumes:
      - "./bff:/app"
